### PR TITLE
Pulled new entries.json from Apple

### PR DESCRIPTION
**Pull request by fefrei**
Apple has released new videos! The feed is here: http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json

This PR is entirely untested, but might be enough to support the new videos.

### CODE REVIEW

**Comment by graysky2** [comment]
Nice!  How did you come to learn of these curiously.

**Comment by fefrei** [comment]
It was mentioned on some news site.
(Looks like you also need to update some the checksums file...)

**Comment by enen92** [comment]
In fact to support the new videos a few more changes have to be made. I'll close this PR and create a script to automate either the entries.json and the checksums. Also implementing all the needed changes at the moment. Thanks and sorry for closing it.

**Comment by fefrei** [comment]
No reason to be sorry – the PR was meant as a way to notify you of the new videos while also having a (mostly clueless) try to fix it.
Thanks for the awesome screensaver and taking the time to update it 👍

**Comment by enen92** [comment]
Fixed here: https://github.com/enen92/screensaver.atv4/commit/7daa900e5cc4c9f7a47df7be9009d093686c39e7

Thanks for the headsup

**Pull request closed without merging**
