### PR TITLE
update for py3 and kodi 19 compatibility

### PR DESCRIPTION
**Pull request by graysky2**
also chmod -x several files that do not need this flag

### CODE REVIEW

**Comment by graysky2** [comment]
I believe this fixes https://github.com/enen92/screensaver.atv4/issues/45

**Comment by aerickson** [comment]
Confirmed working for me. Thanks!

**Comment by kubedzero** [comment]
Confirmed working for me as well. 

- I started with a clean install of Kodi 19 Matrix on Windows 10. 
- I then went to the folder `%appdata%/Kodi/addons/` (or `C:\Users\KZ\AppData\Roaming\Kodi\addons\`) and created a new subfolder `screensaver.aerial` within. 
- I then downloaded the repository at the commit linked above https://github.com/graysky2/screensaver.atv4/archive/38c891014bafefa6c56fff335e951e7e931320d1.zip
- I extracted and then copied all the files into the `screensaver.aerial` folder I created. So `addon.xml` should be located under `C:\Users\KZ\AppData\Roaming\Kodi\addons\screensaver.aerial\addon.xml`
- I started Kodi and sure enough, under Add-ons I now see Aerial. Expanding its information, I see version 1.5.1

Thanks @graysky2  for digging into this and providing a solution! Hopefully @enen92  can merge this soon so users don't have to go to Github and patch the files manually.

**Review by enen92 — APPROVED** [review]

**Comment by enen92** [comment]
it doesn't fix https://github.com/enen92/screensaver.atv4/issues/45
There's far more to do than just adjusting the xbmc.python version in addon.xml

**Comment by graysky2** [comment]
> it doesn't fix #45
> There's far more to do than just adjusting the xbmc.python version in addon.xml

I am running your latest git commit and am finding it to be fully functional on 19.0.

**Comment by kubedzero** [comment]
> finding it to be fully functional on 19.0.


Same! Though I'm working on some other changes, and will hopefully have a PR soon.

**Comment by enen92** [comment]
@kubedzero a new version was submitted to matrix, if you plan to work on features make sure you use the current master

**Comment by kubedzero** [comment]
@enen92 I'm disappointed you didn't push the commits earlier, this undoes a lot of the work I've done in the past day 🤣 

I guess I'll look at the new code and see what still needs fixing.

**Pull request merged**
